title:             Sinai Library Digitization Project
email:
description:       A collaborative project with St. Catherine's Monastery, UCLA Digital Library, and Early Manuscripts Electronic Library
author:            UCLA Digital Library
baseurl:           /sldp/
url:

# Social Profiles
twitter_username:  UCLADigLib
instagram_username: UCLALibrary
github_username:   UCLALibrary
facebook_username: UCLADigitalLibrary

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
