title:             Sinai Library Digitization Project
subtitle:          Arabic and Syriac Manuscripts of St. Catherine's Monastery
email:
description:       A collaborative digitization project between St. Catherine's Monastery in Sinai, the UCLA Digital Library, and the Early Manuscripts Electronic Library
author:            UCLA Digital Library
baseurl:           /sldp/
url:

# Social Profiles
twitter_username:  UCLADigLib
instagram_username: UCLALibrary
# github_username:   UCLALibrary
facebook_username: UCLADigLib

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
