title:             Clean Blog
email:             your-email@example.com
description:       A Blog Theme by Start Bootstrap
author:            Start Bootstrap
baseurl:           /sldp/
url:

# Social Profiles
twitter_username:  UCLADigLib
instagram_username: UCLALibrary
github_username:   UCLALibrary
facebook_username: UCLADigitalLibrary

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
